//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vaccine()
        {
            this.vaccinated = new HashSet<vaccinated>();
        }
    
        public int vaccine_id { get; set; }
        public string name_vaccine { get; set; }
        public int manufacturer_id { get; set; }
        public int count_vaccine { get; set; }
        public Nullable<System.DateTime> manufacturing_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    
        public virtual manufacturer manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaccinated> vaccinated { get; set; }
    }
}
