//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccinated
    {
        public int datails_id { get; set; }
        public int entity_id { get; set; }
        public int vaccine_id { get; set; }
        public System.DateTime receiving_date { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual vaccine vaccine { get; set; }
    }
}
